language: node_js
node_js:
 - "node"

services:
  - docker

addons:
  firefox: "latest"

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - npm install mocha
  - docker-compose up -d
  - echo $PATH

script:
  - whereis geckodriver
  - whereis firefox
  - geckodriver --version
  - firefox --version
  - selenium-webdriver --version
  #- mostrar version de gecko y firefox y selenium
  - export MOZ_HEADLESS=1
  - npm run test
  - npm run browser-test
