language: node_js
node_js:
 - "node"

services:
  - docker

addons:
  firefox: "latest"
  browserstack:
    username: "tomasmedina1"
    access_key: "BROWSERSTACK_KEY"

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - npm install mocha
  - npm install nyc
  - docker-compose up -d
  - echo $PATH

script:
  - npm run test
  - npm run browserstack-test
#- docker-compose exec app nyc --reporter=lcovonly --reporter=text mocha
