version: '3'
services:
  app:
    image: app_test
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME:Tomas"
      - "MONGO_INITDB_ROOT_PASSWORD:Contrasenia"
      - "MONGO_INITDB_DATABASE:bandsDB"
